INSERT INTO `city` (`id`,`name`,`zipcode`) VALUES
(1, 'city 1', 'zipcode 1'),
(2, 'city 2', 'zipcode 2'),
(3, 'city 3', 'zipcode 3'),
(4, 'city 4', 'zipcode 4'),
(5, 'city 5', 'zipcode 5'),
(6, 'city 6', 'zipcode 6'),
(7, 'city 7', 'zipcode 7'),
(8, 'city 8', 'zipcode 8'),
(9, 'city 9', 'zipcode 9');